import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div>
          <Link href="/" className="text-blue-500 hover:underline"> home</Link>
          <Link href="/about" className="text-blue-500 hover:underline"> about</Link>
          <Link href="/servis" className="text-blue-500 hover:underline"> servis</Link>
          <Link href="/contoh" className="text-blue-500 hover:underline"> contoh</Link>
          <Link href="/contact" className="text-blue-500 hover:underline"> contact</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
